# -*- coding: utf-8 -*-
"""
SheVan multipage — Part 2: Content data.
Each piece is a dict that the template functions consume to render
the actual HTML. Texts come from the client's brief whenever possible.
"""

# ============================================================
# CAMPERIZACIONES
# ============================================================

GRAN_VOLUMEN = {
    "slug": "gran-volumen",
    "category": "Camperizaciones",
    "category_slug": "camperizaciones",
    "title": "Gran Volumen",
    "title_long": "Tu casa sin límites. Camperización de Gran Volumen.",
    "title_seo": "Camperización Gran Volumen (Ducato, Sprinter, Crafter) en Sabadell, Barcelona | SheVan",
    "meta": "Camperización completa de furgonetas de gran volumen (Ducato, Sprinter, Crafter, Jumper, Boxer) en Sabadell. Distribución a la carta, baño completo, autonomía total. Pide presupuesto.",
    "lead": "¿Tienes una Ducato, Jumper, Crafter o similar? Es el lienzo perfecto para crear un hogar completo. En SheVan nos especializamos en transformar furgonetas de gran volumen desde cero, aprovechando cada rincón para que no tengas que renunciar a nada.",
    "intro": "No creemos en las distribuciones \"en serie\". Trabajamos contigo para diseñar un espacio que se adapte al 100% a tus necesidades.",
    "features": [
        {"title": "Distribución a la carta", "desc": "Salones convertibles, camas fijas o elevables, y garajes optimizados para tu equipo deportivo."},
        {"title": "Baño completo", "desc": "Instalación de cabinas de ducha rígidas con agua caliente y sanitarios."},
        {"title": "Autonomía total", "desc": "Sistemas eléctricos de alta capacidad, cocinas equipadas y depósitos de gran capacidad para perderte durante días."},
        {"title": "Acabados premium", "desc": "Materiales ligeros y resistentes con una estética cuidada que te hará olvidar que estás dentro de un vehículo."},
    ],
    "quote": "De furgón industrial a hogar de ensueño. Diseñamos la distribución que dicta tu estilo de vida, no la que dicta el manual.",
    "brands": ["Fiat Ducato", "Peugeot Boxer", "Citroën Jumper", "VW Crafter", "Mercedes Sprinter", "Renault Master", "Ford Transit"],
    "cta_text": "Pide presupuesto para tu Gran Volumen",
    "image_label": "Furgo Gran Volumen camperizada",
    "icon": "van-large",
}

MEDIANAS_PEQUENAS = {
    "slug": "medianas-pequenas",
    "category": "Camperizaciones",
    "category_slug": "camperizaciones",
    "title": "Medianas y Pequeñas",
    "title_long": "Versatilidad en movimiento. Furgonetas medianas y pequeñas.",
    "title_seo": "Camperización VW T6, Vito, Trafic, Berlingo en Sabadell, Barcelona | SheVan",
    "meta": "Camperización de furgonetas medianas y compactas (VW T5/T6, Vito, Trafic, Custom, Berlingo) en Sabadell. Mobiliario modular, techos elevables, neveras de compresor. Pide presupuesto.",
    "lead": "Máxima libertad en formato compacto. ¿Buscas una furgoneta ágil para tu día a día que se convierta en refugio al llegar el viernes?",
    "intro": "En SheVan sacamos el máximo partido a cada centímetro de las furgonetas medianas y pequeñas. Nos especializamos en crear soluciones inteligentes que combinan la conducción de un turismo con la esencia de una casa.",
    "features": [
        {"title": "Mobiliario Modular y Kits", "desc": "Diseños que aprovechan el espacio al milímetro. Desde muebles laterales fijos hasta kits desmontables para que tu furgo mantenga su versatilidad original."},
        {"title": "Neveras de Compresor", "desc": "Olvida el hielo. Instalamos neveras de alto rendimiento (fijas o en cajón extraíble) para que tus alimentos estén siempre perfectos, incluso en pleno verano."},
        {"title": "Techos Elevables", "desc": "La magia de ganar una habitación extra y poder estar de pie dentro de tu furgo. Ganamos confort y ventilación sin perder agilidad."},
        {"title": "Sistemas de Asiento-Cama", "desc": "Soluciones homologadas para viajar y dormir con total seguridad."},
        {"title": "Instalaciones Invisibles", "desc": "Baterías auxiliares, calefacciones estacionarias y tomas de agua optimizadas para no restar espacio de carga, y paneles solares para asegurar siempre buena autonomía."},
    ],
    "quote": "Pequeña por fuera, infinita por dentro. En SheVan diseñamos la compañera perfecta para tus escapadas improvisadas.",
    "brands": ["VW Transporter T4/T5/T6", "Mercedes Vito", "Mercedes Clase V", "Ford Transit Custom", "Renault Trafic", "Nissan Primastar", "Opel Vivaro", "Citroën Berlingo", "Peugeot Rifter", "Toyota Proace City", "VW Caddy"],
    "cta_text": "Pide presupuesto para tu camper compacta",
    "image_label": "Furgo mediana camperizada",
    "icon": "van-small",
}

HOMOLOGACIONES = {
    "slug": "homologaciones",
    "category": "Camperizaciones",
    "category_slug": "camperizaciones",
    "title": "Homologaciones",
    "title_long": "Homologación de tu camper, sin papeleos.",
    "title_seo": "Homologación de furgonetas camper en Sabadell, Barcelona | SheVan",
    "meta": "Homologación oficial de tu camperización en Sabadell. Tramitamos los cambios de ITV y vehículo vivienda para que tu furgo esté en regla. Pide presupuesto.",
    "lead": "Convertir una furgoneta en vivienda no es solo construirla bien — también hay que registrarla bien. En SheVan nos encargamos de toda la parte burocrática para que tu camper esté correctamente homologada como vehículo vivienda.",
    "intro": "Trabajamos con ingenieros titulados que firman los proyectos técnicos y nos coordinamos con la ITV para que tú no tengas que preocuparte por nada.",
    "features": [
        {"title": "Proyecto técnico de reforma", "desc": "Documentación firmada por ingeniero acreditado para presentar en Industria."},
        {"title": "Cambio de clasificación ITV", "desc": "Pasamos tu vehículo de furgoneta a vivienda con todos los trámites oficiales."},
        {"title": "Asesoramiento previo", "desc": "Te explicamos los requisitos antes de empezar para que el proyecto se diseñe ya pensando en homologar."},
        {"title": "Coordinación completa", "desc": "Nosotros gestionamos las visitas a la ITV y cualquier requerimiento adicional."},
    ],
    "quote": "Una camper bien construida merece estar bien registrada. Te lo dejamos todo en regla.",
    "brands": [],
    "cta_text": "Consulta tu homologación",
    "image_label": "Documentación y placa ITV",
    "icon": "doc",
}

CAMPERIZACIONES_SUB = [GRAN_VOLUMEN, MEDIANAS_PEQUENAS, HOMOLOGACIONES]


# ============================================================
# ACCESORIOS
# ============================================================

ACCESORIOS = [
    {
        "slug": "segunda-bateria",
        "category": "Accesorios e instalaciones",
        "subcategory": "Eléctrica",
        "category_slug": "accesorios",
        "title": "Segunda Batería",
        "title_long": "Segunda Batería: el corazón de tu autonomía.",
        "title_seo": "Instalación de Segunda Batería Auxiliar (Litio LiFePO4 / AGM) para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación profesional de baterías auxiliares Litio LiFePO4 y AGM para campers y autocaravanas en Sabadell. Sistemas de carga inteligente. Pide presupuesto a SheVan.",
        "lead": "¿Alguna vez has tenido que apagar la nevera por miedo a no poder arrancar el motor a la mañana siguiente?",
        "intro": "En SheVan eliminamos esa inseguridad instalando sistemas de energía auxiliar independientes. Se acabó el ir contando los amperios; instalamos la capacidad que tu ritmo de vida necesita para que el confort no se detenga cuando apagues el contacto.",
        "body": "No instalamos simplemente una batería; diseñamos un sistema de carga inteligente que alimenta tus luces, tomas USB y lo que necesites de forma segura. Trabajamos con tecnología avanzada Litio (LiFePO4) y AGM, asegurando que cada conexión sea impecable y duradera. Tu única preocupación será decidir dónde quieres ver el próximo amanecer con la tranquilidad de tener energía de sobra.",
        "features": [],
        "quote": "",
        "image_label": "Sistema de batería auxiliar instalado",
        "icon": "battery",
    },
    {
        "slug": "paneles-solares",
        "category": "Accesorios e instalaciones",
        "subcategory": "Eléctrica",
        "category_slug": "accesorios",
        "title": "Paneles Solares",
        "title_long": "Libertad que viene del cielo.",
        "title_seo": "Instalación de Paneles Solares Fotovoltaicos para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de paneles solares MPPT rígidos y flexibles para campers y autocaravanas en Sabadell. Sistemas fotovoltaicos para autonomía total. Pide presupuesto.",
        "lead": "Olvídate de depender de enchufes externos o de entrar en campings solo para cargar tus sistemas.",
        "intro": "Con la instalación fotovoltaica de SheVan, tu furgoneta se convierte en una fuente de energía inagotable. Es la solución perfecta para los que buscan perderse en la naturaleza sin renunciar a la tecnología.",
        "body": "Instalamos paneles de alta eficiencia con reguladores inteligentes <strong>MPPT</strong>, que maximizan la captación solar incluso en condiciones de poca luz. Ya sea una placa rígida sobre una baca o una flexible para mantener la aerodinámica, nos aseguramos de que el sol trabaje para ti mientras tú te relajas. Es energía silenciosa, sostenible y, sobre todo, la llave para que tus escapadas no tengan fecha de caducidad.",
        "features": [],
        "quote": "",
        "image_label": "Panel solar en techo de camper",
        "icon": "sun",
    },
    {
        "slug": "inversor",
        "category": "Accesorios e instalaciones",
        "subcategory": "Eléctrica",
        "category_slug": "accesorios",
        "title": "Inversor y Tomas 230V",
        "title_long": "Enchufados a la aventura.",
        "title_seo": "Inversor de Onda Senoidal Pura y Tomas 230V para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de inversores de Onda Senoidal Pura y tomas 230V en campers y autocaravanas en Sabadell. Lleva la corriente de tu casa a cualquier lugar. Pide presupuesto.",
        "lead": "¿Quién dijo que viajar en camper significa renunciar a tus pequeños lujos?",
        "intro": "Con un inversor de corriente, transformamos la energía de tu batería en un enchufe convencional como el de tu salón. Desde el ordenador para editar tus fotos hasta la cafetera para el primer espresso del día, llevamos la versatilidad de tu casa a cualquier lugar del mapa.",
        "body": "En SheVan priorizamos la seguridad de tus dispositivos. Por eso, solo instalamos inversores de <strong>Onda Senoidal Pura</strong>, garantizando una corriente estable y limpia que protege tus equipos electrónicos más delicados. Integramos las tomas de corriente de forma estética y funcional en el mobiliario, para que tengas potencia siempre a mano sin cables de por medio.",
        "features": [],
        "quote": "",
        "image_label": "Inversor y tomas instaladas",
        "icon": "plug",
    },
    {
        "slug": "calefaccion",
        "category": "Accesorios e instalaciones",
        "subcategory": "Climatización",
        "category_slug": "accesorios",
        "title": "Calefacción Estacionaria",
        "title_long": "Tu refugio contra el frío.",
        "title_seo": "Calefacción Estacionaria Webasto y Autoterm para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de calefacción estacionaria diésel Webasto, Autoterm y Nordkapp en campers y autocaravanas en Sabadell. Pide presupuesto.",
        "lead": "¿Te imaginas despertar en medio de un paisaje nevado y que el interior de tu furgo esté a una temperatura perfecta?",
        "intro": "No dejes que el invierno dicte cuándo puedes viajar. En SheVan instalamos sistemas de calefacción autónoma diésel que funcionan directamente con el depósito de tu vehículo, consumiendo el mínimo y ofreciendo la máxima seguridad.",
        "body": "Somos especialistas en las marcas líderes del sector: <strong>Webasto, Autoterm y Nordkapp</strong>. Desde sistemas con control digital hasta gestión remota desde el móvil, nos encargamos de una instalación limpia y certificada. Porque viajar con frío es sobrevivir, pero viajar con calefacción es vivir la aventura como te mereces.",
        "features": [],
        "quote": "",
        "image_label": "Calefacción estacionaria con mando digital",
        "icon": "fire",
    },
    {
        "slug": "aire-acondicionado",
        "category": "Accesorios e instalaciones",
        "subcategory": "Climatización",
        "category_slug": "accesorios",
        "title": "Aire Acondicionado",
        "title_long": "Frescor sin límites (12V y 230V).",
        "title_seo": "Aire Acondicionado 12V y 230V para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de aire acondicionado 12V y 230V en campers y autocaravanas en Sabadell. Autonomía total con sistemas a baterías. Pide presupuesto.",
        "lead": "El calor extremo puede arruinar cualquier escapada, pero en SheVan tenemos la solución para que el verano no te detenga.",
        "intro": "Realizamos instalaciones de aire acondicionado tanto en furgonetas camper como en autocaravanas, adaptándonos a tu forma de viajar.",
        "body": "Ya sea en el techo o integrado en el interior, estudiamos el espacio de tu vehículo para que el flujo de aire sea óptimo. Mantén tu casa con ruedas fresca, silenciosa y lista para el descanso, incluso bajo el sol más intenso.",
        "features": [
            {"title": "Sistemas a 12V", "desc": "La revolución para los que buscan autonomía total. Disfruta del aire frío alimentado directamente por tus baterías, sin necesidad de estar enchufado a un camping."},
            {"title": "Sistemas a 230V", "desc": "Potencia máxima para estancias prolongadas con conexión externa."},
        ],
        "quote": "",
        "image_label": "Aire acondicionado en techo de camper",
        "icon": "snowflake",
    },
    {
        "slug": "aislamiento",
        "category": "Accesorios e instalaciones",
        "subcategory": "Aislamiento",
        "category_slug": "accesorios",
        "title": "Aislamiento Térmico",
        "title_long": "La base del confort.",
        "title_seo": "Aislamiento Térmico Kaiflex para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Aislamiento térmico de campers y autocaravanas con Kaiflex en Sabadell. Rompemos puentes térmicos, reducimos ruido. Pide presupuesto a SheVan.",
        "lead": "De nada sirve calentar o enfriar tu vehículo si el calor se escapa por la chapa.",
        "intro": "El aislamiento es la inversión más importante en cualquier camperización. En SheVan desnudamos el furgón para aplicar una capa técnica de Kaiflex de alta densidad, cubriendo cada nervio y rincón para romper los puentes térmicos.",
        "body": "Este tratamiento no solo mantiene la temperatura interior, sino que reduce drásticamente el ruido exterior y de rodadura, transformando tu furgoneta en un espacio silencioso y acogedor. Es la diferencia entre dormir en una caja de metal o dormir en un verdadero hogar.",
        "features": [],
        "quote": "",
        "image_label": "Furgo con Kaiflex aplicado",
        "icon": "shield",
    },
    {
        "slug": "ventanas-claraboyas",
        "category": "Accesorios e instalaciones",
        "subcategory": "Apertura",
        "category_slug": "accesorios",
        "title": "Ventanas y Claraboyas",
        "title_long": "Tu conexión con el exterior.",
        "title_seo": "Instalación de Ventanas y Claraboyas para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de ventanas y claraboyas estancas para campers y autocaravanas en Sabadell. Luz natural, ventilación, control de humedad. Pide presupuesto.",
        "lead": "¡No hay nada como la sensación de libertad que da estar rodeado de naturaleza, incluso cuando estás dentro de tu furgoneta!",
        "intro": "Instalar claraboyas y ventanas es la mejor manera de dejar entrar la luz natural y el aire fresco en tu hogar sobre ruedas, eliminando la sensación de espacio cerrado y conectándote directamente con el paisaje.",
        "body": "Imagina despertar con los primeros rayos de sol entrando por tu claraboya, o disfrutar de una brisa fresca mientras preparas el desayuno con vistas al mar. Pero no es solo estética: una buena ventilación es la clave para reducir la humedad y la condensación, manteniendo un ambiente saludable y cómodo en cualquier estación. En SheVan seleccionamos el modelo perfecto para tu vehículo y te garantizamos una instalación impecable y estanca, para que tú solo te preocupes de elegir hacia dónde quieres mirar hoy.",
        "features": [],
        "quote": "",
        "image_label": "Claraboya vista desde el interior",
        "icon": "window",
    },
    {
        "slug": "techo-elevable",
        "category": "Accesorios e instalaciones",
        "subcategory": "Espacio",
        "category_slug": "accesorios",
        "title": "Techo Elevable",
        "title_long": "Tu habitación con vistas.",
        "title_seo": "Instalación de Techo Elevable Reimo, SCA, Atek en Sabadell | SheVan",
        "meta": "Instalación de techos elevables Reimo, SCA y Atek para campers en Sabadell. Gana una habitación extra. Pide presupuesto a SheVan.",
        "lead": "¿Sientes que a tu aventura le falta espacio?",
        "intro": "El techo elevable es la transformación definitiva para quienes buscan la agilidad de una furgoneta compacta sin renunciar a la amplitud de una casa. En SheVan transformamos tu vehículo en un espacio de dos plantas en cuestión de segundos, permitiéndote estar de pie en el interior y disfrutar de una cama doble adicional con la máxima comodidad.",
        "body": "Trabajamos con fabricantes como: <strong>Reimo, SCA y Atek</strong>. Sin duda son una de las mejores inversiones para ampliar tus horizontes y disfrutar de una habitación con las mejores vistas del mundo: las que tú elijas al aparcar.",
        "features": [],
        "quote": "",
        "image_label": "Furgo con techo elevable abierto",
        "icon": "expand",
    },
    {
        "slug": "cierres-seguridad",
        "category": "Accesorios e instalaciones",
        "subcategory": "Seguridad",
        "category_slug": "accesorios",
        "title": "Cierres de Seguridad",
        "title_long": "Tranquilidad allá donde vayas.",
        "title_seo": "Cierres de Seguridad Interiores y Exteriores para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de cierres de seguridad interiores y exteriores en campers y autocaravanas en Sabadell. Protección discreta y efectiva. Pide presupuesto.",
        "lead": "La libertad de viajar en camper no tiene precio, y tu seguridad tampoco.",
        "intro": "En SheVan sabemos que tu furgoneta no es solo un vehículo, es tu hogar y donde guardas tus sueños (y tu equipo). Por eso, ofrecemos la instalación de sistemas de seguridad avanzados que te permitirán dormir y dejar tu furgo aparcada con total tranquilidad.",
        "body": "Instalamos <strong>cierres de seguridad tanto interiores como exteriores</strong>, diseñados específicamente para las puertas de cabina, portones laterales y traseros. Trabajamos con cierres técnicos que refuerzan los puntos críticos de tu modelo, evitando aperturas no deseadas de forma discreta y efectiva. Porque la verdadera aventura se disfruta más cuando sabes que tú y los tuyos estáis protegidos, busques el destino que busques.",
        "features": [],
        "quote": "",
        "image_label": "Cierres interiores y exteriores instalados",
        "icon": "lock",
    },
    {
        "slug": "toldo-portabicis",
        "category": "Accesorios e instalaciones",
        "subcategory": "Exterior",
        "category_slug": "accesorios",
        "title": "Toldos y Portabicis",
        "title_long": "Amplía tu zona de confort.",
        "title_seo": "Instalación de Toldos Fiamma, Thule y Portabicis para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de toldos laterales Fiamma y Thule, y portabicicletas reforzados para campers y autocaravanas en Sabadell. Pide presupuesto.",
        "lead": "La aventura no termina dentro de la furgoneta; el exterior es tu nuevo salón.",
        "intro": "Con nuestros toldos laterales de marcas líderes como Fiamma o Thule, creas un porche instantáneo donde disfrutar de la sombra y el aire libre en segundos, protegiéndote del sol o de la lluvia ligera.",
        "body": "Y si lo tuyo es el movimiento, instalamos <strong>portabicicletas reforzados y adaptados</strong> específicamente a la estructura de tu vehículo. En SheVan nos aseguramos de que cada accesorio exterior sea aerodinámico, seguro y esté listo para soportar miles de kilómetros. Equipa tu furgo con todo lo necesario para que tu campamento sea el más completo de la ruta.",
        "features": [],
        "quote": "",
        "image_label": "Furgo con toldo desplegado y portabicicletas",
        "icon": "umbrella",
    },
    {
        "slug": "suspension-neumatica",
        "category": "Accesorios e instalaciones",
        "subcategory": "Mecánica",
        "category_slug": "accesorios",
        "title": "Suspensión Neumática",
        "title_long": "El siguiente nivel de conducción.",
        "title_seo": "Instalación de Suspensión Neumática para Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Instalación de suspensión neumática para campers y autocaravanas en Sabadell. Mejor estabilidad, seguridad y nivelación. Pide presupuesto.",
        "lead": "¿Notas que tu furgoneta balancea mucho con el viento, o que la parte trasera se hunde cuando vas cargado?",
        "intro": "La suspensión neumática es la solución técnica que cambiará por completo tu forma de conducir. En SheVan instalamos sistemas neumáticos que mejoran la estabilidad, la seguridad y el confort de marcha de tu camper o autocaravana.",
        "body": "Este sistema te permite nivelar el vehículo fácilmente cuando estás acampado y absorber mucho mejor las irregularidades de la carretera durante el viaje. Es una mejora fundamental para proteger la estructura de tu vehículo y disfrutar de una conducción mucho más suave y segura, incluso en los terrenos más exigentes. ¡Dale a tu furgo la estabilidad que se merece!",
        "features": [],
        "quote": "",
        "image_label": "Balona / panel de control de suspensión",
        "icon": "wave",
    },
]


# ============================================================
# TALLER (Reparaciones)
# ============================================================

TALLER_SECCIONES = [
    {
        "slug": "electrica",
        "category": "Taller y reparaciones",
        "subcategory": "Eléctrica",
        "category_slug": "taller",
        "title": "Reparaciones Eléctricas",
        "title_long": "Reparaciones y mejoras eléctricas para camper y autocaravana.",
        "title_seo": "Reparación Eléctrica de Camper y Autocaravana en Sabadell, Barcelona | SheVan",
        "meta": "Reparación de instalaciones eléctricas en campers y autocaravanas en Sabadell. Saneamos sistemas antiguos, optimizamos a Litio. Reserva cita.",
        "lead": "¿Tu batería auxiliar no carga? ¿Un fusible te está dando problemas o quieres actualizar tu sistema a Litio?",
        "intro": "Trabajamos con campers y autocaravanas: saneamos instalaciones antiguas, localizamos consumos fantasma y optimizamos tu sistema eléctrico para que vuelvas a ser 100% autónomo.",
        "body": "Diagnosticamos a fondo la instalación, identificamos los puntos de fallo, y te proponemos una solución duradera — no un parche. Si tu sistema necesita actualizarse a tecnologías más modernas (Litio LiFePO4, MPPT, monitoreo inteligente), también te lo planteamos.",
        "features": [],
        "quote": "",
        "image_label": "Diagnóstico eléctrico en taller",
        "icon": "bolt",
    },
    {
        "slug": "agua",
        "category": "Taller y reparaciones",
        "subcategory": "Agua",
        "category_slug": "taller",
        "title": "Sistemas de Agua",
        "title_long": "Reparación de sistemas de agua en camper y autocaravana.",
        "title_seo": "Reparación de Sistemas de Agua en Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Reparación de circuitos de agua, bombas de presión, depósitos y boilers en campers y autocaravanas en Sabadell. Reserva cita en taller.",
        "lead": "Solucionamos fugas en circuitos, averías en bombas de presión, problemas de estanqueidad en depósitos o fallos en el agua caliente (boilers).",
        "intro": "Si tu sistema de aguas limpias o grises necesita una revisión, nosotros lo dejamos como nuevo.",
        "body": "Trabajamos sobre el sistema completo: depósitos, bombas, válvulas, grifería y circuito de agua caliente. Si hay un goteo persistente o la bomba pierde presión, lo localizamos y lo arreglamos sin ir cambiando piezas a ciegas.",
        "features": [],
        "quote": "",
        "image_label": "Bomba de agua y circuito",
        "icon": "drop",
    },
    {
        "slug": "filtraciones",
        "category": "Taller y reparaciones",
        "subcategory": "Estanqueidad",
        "category_slug": "taller",
        "title": "Filtraciones y Humedades",
        "title_long": "El agua es el peor enemigo de una camperización.",
        "title_seo": "Reparación de Filtraciones y Humedades en Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Localización y sellado de filtraciones en campers y autocaravanas en Sabadell. Re-sellado de claraboyas, A/C, pasamuros. Reserva cita.",
        "lead": "Si has detectado una mancha, humedad o goteo en tu camper o autocaravana, actuar rápido es clave.",
        "intro": "Somos expertos en la localización y sellado de filtraciones en los puntos más críticos de tu vehículo vivienda — sea camper o autocaravana.",
        "body": "Cada filtración tiene su origen y su tratamiento — no vale con echar silicona y rezar. Diagnosticamos el punto exacto de entrada, retiramos el sellado antiguo, y volvemos a estanquizar con materiales adecuados al elemento (claraboya, ventana, A/C, pasamuros). Es prevención y reparación a la vez.",
        "features": [
            {"title": "Claraboyas y ventanas", "desc": "Re-sellado preventivo y correctivo con materiales de alta resistencia."},
            {"title": "Sistemas de Aire Acondicionado", "desc": "Reparación de fugas por condensación o mal sellado en techo."},
            {"title": "Pasamuros y juntas", "desc": "Revisión total de la estanqueidad exterior para evitar daños estructurales en el mobiliario."},
        ],
        "quote": "",
        "image_label": "Sellado de claraboya en techo",
        "icon": "drop-shield",
    },
    {
        "slug": "gas",
        "category": "Taller y reparaciones",
        "subcategory": "Gas",
        "category_slug": "taller",
        "title": "Instalaciones de Gas",
        "title_long": "La seguridad es lo primero. Gas en camper y autocaravana.",
        "title_seo": "Reparación de Instalaciones de Gas en Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Reparación y revisión de instalaciones de gas en campers y autocaravanas en Sabadell. Cumplimiento de normativa para tu seguridad. Reserva cita.",
        "lead": "Reparamos averías en sistemas de gas tanto en campers como en autocaravanas, revisamos fogones y nos aseguramos de que toda la instalación cumpla con la normativa.",
        "intro": "Para que viajes con total protección y sin riesgos.",
        "body": "El gas es un sistema crítico: una fuga, una conexión mal hecha o una pieza fuera de norma puede ser un problema serio. Nuestro trabajo es revisar la instalación entera, sustituir lo que esté gastado o no cumpla, y dejarte la documentación correspondiente.",
        "features": [],
        "quote": "",
        "image_label": "Instalación de gas con detector",
        "icon": "flame",
    },
    {
        "slug": "mobiliario",
        "category": "Taller y reparaciones",
        "subcategory": "Mobiliario",
        "category_slug": "taller",
        "title": "Mobiliario y Herrajes",
        "title_long": "Reparación de mobiliario y herrajes en camper y autocaravana.",
        "title_seo": "Reparación de Mobiliario y Herrajes en Camper y Autocaravana en Sabadell | SheVan",
        "meta": "Reparación de bisagras, guías, cierres y mobiliario en campers y autocaravanas en Sabadell. Pequeñas modificaciones a medida. Reserva cita.",
        "lead": "El uso y el paso del tiempo pueden desgastar tu camper o autocaravana.",
        "intro": "Reparamos bisagras, guías de cajones, cierres de armarios o cualquier desperfecto en la madera.",
        "body": "También realizamos pequeñas modificaciones en el mobiliario existente para que se adapte mejor a tu uso actual. Si llevas tiempo viviendo con tu camper y has visto que falta una balda aquí o un cajón allá, te lo añadimos sin tener que rehacerlo todo.",
        "features": [],
        "quote": "",
        "image_label": "Mobiliario interior reparado",
        "icon": "tools",
    },
]
